### ISSUE TITLE
Pictures aren't loading on blog posts when live

### ISSUE THREAD

**Issue by Frijol** [datatogether/website#106]

**Comment by lightandluck** [comment]
Try upgrading hugo in our [Circle config](https://github.com/datatogether/website/blob/ebd8700c638575322bf18ddd45a25df3ac6ff87b/.circleci/config.yml#L10) to whatever version you're using. 

Or we can try this hack: https://anaulin.org/blog/hugo-raw-html-shortcode/. I know this works.

**Comment by Frijol** [comment]
Tried upgrading hugo in Circle config and now hugo's deploy step is broken, even when I change it back to the old hugo version :( https://app.circleci.com/pipelines/github/datatogether/website/175/workflows/d5579775-d71e-48d6-bf45-549b8193c974/jobs/178 it says it doesn't have a config file.

**Comment by Frijol** [comment]
Oh hm, it does build and push to the gh-pages branch, but the config file is indeed missing from the gh-pages branch and has been posting errors for quite a while now.

https://app.circleci.com/pipelines/github/datatogether/website?branch=gh-pages

I'll split this out into a new issue.

**Comment by lightandluck** [comment]
Something else to try - It looks like it's building from a docker image of hugo from here: https://github.com/cibuilds/hugo, so I think you'd have to use the folder name: `0.79`, instead of the version name `0.79.1`.

**Comment by Frijol** [comment]
hm, worth a shot but also didn't work. I'll try the shortcode

**Comment by Frijol** [comment]
shortcode isn't working either :( ...but also now the images aren't loading locally either without the shortcodes, so I'll throw those into all the posts

**Comment by Frijol** [comment]
oh no wait it worked! It just took a while to propagate or something. Yay!
