### ISSUE TITLE
Publishing Updates

### ISSUE THREAD

**Issue by b5** [datatogether/website#11]
I think we should avoid constantly having to bother @lgierth to repoint the IPNS entry for this page on updates. Some options include:

* replicate a script like the one contained in ipfs/website that makes updates extra easy for someone at protocol to perform
* we set up an IPFS gateway, request a one time DNS point at the IPNS entry of that gateway, self-manage updates
* switch to a "more traditional" static hosting solution 😢

**Comment by ghost** [comment]
Hey,
in lack of good publishing tooling I'd suggest we point the datatogether.org dnslink record to a domain that you control, e.g. we could set it to `dnslink=/ipns/b5.example.net`, and by setting `TXT _dnslink.b5.example.net dnslink=/ipfs/somehash` on that domain you can control what /ipns/datatogether.org recursively resolves too. That also nicely separates content from gateway hosting.

**Comment by dcwalk** [comment]
Hey @b5 is this something we could revisit in the coming week(ish)? 
It would be great to get those artwork changes up 💃

**Comment by ghost** [comment]
Update: we can now actually add more accounts to individual domains in DNSimple. So alternatively to what's described above you can also make a DNSimple account and I can invite it to manage the datatogether.org domain.

**Comment by b5** [comment]
@dcwalk, absolutely! @lgierth thanks so much for the update, that'd be lovely. I'm b5 on dnssimple as well :)

**Comment by ghost** [comment]
@b5 I need an email address

**Comment by b5** [comment]
ah I see. How's this for nerdy? Base64 encoded email lololol: YnJlbmRhbkBxcmkuaW8=
(my email is by no means private, just don't want robots 😃 )

**Comment by ghost** [comment]
:) You're all set! I made this little tool (works with an account token) for automating the record updates where neccessary: https://github.com/lgierth/dnslink-dnsimple

**Comment by b5** [comment]
Nice. Just managed to make my first publish, that CLI/script worked like a charm. Thanks for all your help @lgierth!

@dcwalk now that the most recent commit is live and we have a solid workflow for changes, feel free to let me know/PR anything that needs changing. shouldn't take more than 20 minutes to update the site to match merged PRs from here on in.

**Comment by dcwalk** [comment]
Closing this as we got this version up and running, just addressing how to best impement #30
