### ISSUE TITLE
Unpublished trust and private data blog posts

### ISSUE THREAD

**Issue by lightandluck** [datatogether/website#111]
Just a heads up that I set the publish date for the trust (d1ab133ea37928485e143a5fd46589a7d9e4726a) and private data (ebd8700c638575322bf18ddd45a25df3ac6ff87b) posts  after the new year because they're still stubs and I'm not sure what the planned publishing date is. The trust blog was appearing on the live site.

Let's close this issue whenever the correct date is put in for them?

**Comment by Frijol** [comment]
oh, thank you! I forgot to update them
