### ISSUE TITLE
Add links to ESIP "Stronger Together" paper

### ISSUE THREAD

**Issue by flyingzumwalt** [datatogether/website#2]
http://www.esipfed.org/press-releases/stronger-together

Add links and context showing how this connects to the data together pattern.

**Comment by dcwalk** [comment]
Where do you see this fitting @flyingzumwalt ?

**Comment by flyingzumwalt** [comment]
This is an old issue. Given the way we've reshuffled the info for the website and github, this particular info probably belongs better in the datatogether/datatogether repo, where we started building reference materials and documentation, rather than on the website.

**Comment by flyingzumwalt** [comment]
Moved to https://github.com/datatogether/datatogether/issues/45
