### ISSUE TITLE
Revisit dependencies and remove extra libraries, partials, etc...

### ISSUE THREAD

**Issue by dcwalk** [datatogether/website#27]
Hey there, thank you for submitting an issue!

We are trying to keep issues for feature requests and bug reports. Please
complete the following checklist before creating a new one:

- [x] feature request

---

Just poking about and it looks like we have jquery and maybe normalize twice, footer scripts and more that are not relevant to this site.

I feel like this setup was pulled over from another site and we can probably revisit and clean up?

**Comment by dcwalk** [comment]
oh oops, I always forget that hugo doesn't preprocess, looks like gulp was used prior.

**Comment by Frijol** [comment]
It looks like this was resolved in https://github.com/datatogether/website/pull/28
