### ISSUE TITLE
[public record] Tell the background story of public record for "Rescued" data

### ISSUE THREAD

**Issue by flyingzumwalt** [datatogether/website#3]
Tell Story of the emergence of the need for a "data rescue" public record, and the creation of alpha.archivers.space

- all the data rescue efforts happened
- need a way to answer "what has been rescued so far?"
- challenge: reconciling disparate metadata patterns -- original discussion in https://github.com/edgi-govdata-archiving/dataset-registries/issues/1
- upshot: alpha.archivers.space > datatogether/public-record

**Comment by flyingzumwalt** [comment]
Contextualize this screenshot from https://alpha.archivers.space/primers/5b1031f4-38a8-40b3-be91-c324bf686a87 (image below), which does not accurately represent what has or hasn't been achieved by hackathon rescue efforts..

Only shows a piece of the puzzle -- the stuff manually downloaded by data rescuers at hackathons using archivers.space. Doesn't include stuff crawled by IA, which was seeded/nominated by hackathons but not downloaded there. Doesn't include the 30 PB of data and 100 TB of web content from Data Rescue Boulder. Doesn't include the stuff from Project Svalbard.

Need a view that shows all of that stuff together, from the frame of data vulnerability, access, and preservation. That's what the public record should show.

<img width="917" alt="archivers-alpha epa screenshot" src="https://user-images.githubusercontent.com/138930/28638025-9c82b0d2-7211-11e7-88dc-c874e1710dcb.png">

cc @shapironick

**Comment by dcwalk** [comment]
Just moving my comment from the #datatogether slack channel:

> I feel like this screenshot is disengenuous of the work EDGI has done and some reservations about it being used to reflect archiving work:
> 0. this version of the system was never used at a DR event (it came online after all of ‘em!)
> 1. These aren’t the original primers (which are still all gdocs) that were used at DR events
> 2. that URL number doesn’t reflect anything flagged at DRs (@b5 correct me if I’m wrong), it actually is just the whole new archivers v2 crawlers)
> 3. doesn’t reflect what was seeded to IA
> 4. also isn’t mapped to the datarefuge.org site
> 5. “content” there as a concept doesn’t necessarily map to the way objects that were archived at events (it is more granular)
