### ISSUE TITLE
Automatic builds and deploys via Jenkins?

### ISSUE THREAD

**Issue by victorb** [datatogether/website#30]
Hello there!

We're currently making all websites under ipfs/libp2p/ipld/multiformats be automatically built and deployed via Jenkins.

If wanted, we could also activate that for this website. This would give you a link to a preview (via IPFS) for each commit and PR and also automatically update the _dnslink TXT record when changes to master happened. Makes maintenance of the website super simple! 

Let me know if we should activate that for this repository as well.

**Comment by dcwalk** [comment]
Yesssssssss!

cc: @b5

**Comment by b5** [comment]
🎉  @VictorBjelkholm! That would be incredible, especially since I've seen you demo this wonderful new magic. Do you need anything from us, or can you just PR in a big 'ol jenkins config?

**Comment by dcwalk** [comment]
Hey @VictorBjelkholm just circling back on this! Is there anything we can do to assist?

edit: just dropping links of how it works for IPLD so I can find 'em quickly!
https://github.com/ipld/website/blob/master/ci/Jenkinsfile
https://github.com/ipld/website/blob/master/Makefile
https://github.com/ipfs/jenkins

**Comment by b5** [comment]
Quick update on this, @VictorBjelkholm & had a quick checkin on slack. Main reason for the delay is the added overhead of configuration a new Github organization. Expected time to complete is 1-2 weeks, but once that's done adding other datatogether repos to CI will be easier (SO DOPE).

**Comment by dcwalk** [comment]
On May 14 call:
- process stalled
- Protocol Labs folks, @b5 has some dns managing ability
- Will restart conversation

**Comment by victorb** [comment]
Sorry I dragged my legs behind on this, as I was waiting on some other things, I've done this in the meantime: https://github.com/datatogether/website/pull/34

So almost there. Just some permission stuff left.

**Comment by dcwalk** [comment]
Hey! Just following up on this, looks nice on the Jenkins side! (Except for that failing build 😢)

I added #36 just so we have a build badge in our readme, but it looks like the CI bits still have to be set up? @VictorBjelkholm am I correct in assuming you have to do that on your end? 

After that we should update the deployment instructions #37

**Comment by dcwalk** [comment]
ping @VictorBjelkholm could you confirm whether anything on the CI side has to be set up?
