### ISSUE TITLE
Switch to a different build and deploy process

### ISSUE THREAD

**Issue by dcwalk** [datatogether/website#38]
It has taken ~7months to work through an automated deploy process, and it doesn't appear as if it current works. 

Can we build and deploy on a non-IPFS solution while we get an automated process sorted out, given the complexity of this site (low), and the centrality of our hopes to have it used for engagement and messaging (increasing, see https://github.com/datatogether/datatogether/issues/34)?

This could be:
- manual builds onto gh pages
- automated builds onto gh pages
- ?? something fancy on our own VPS?

**Comment by Frijol** [comment]
Related to https://github.com/datatogether/website/issues/39, current plan is to switch to hosting on gh-pages ([tutorial](https://gohugo.io/hosting-and-deployment/hosting-on-github/))

**Comment by Frijol** [comment]
@b5, you mentioned on the last Archiving call that when you switched [Qri's site](https://github.com/qri-io/website) to gh-pages you had to serve it out of a `docs` folder. Per [this tutorial](https://gohugo.io/hosting-and-deployment/hosting-on-github/#types-of-github-pages) that looks like a "project page" approach vs a "user/organization page"– curious to hear why you picked that option– to avoid needing to use submodules? Fewer repos?

It looks simpler than the approach recommended for user/org (and it looks like I don't *have* to name it "docs") but wanted to check in on reasoning.
