### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by Frijol** [datatogether/website#39]
Flagging that the website is down and has been for about a week (or more?).

Based on chat in Slack (thanks @Mr0grog @lightandluck @b5) our site is pinned to the IPFS public gateway (http://gateway.ipfs.io/), which is working, and our dnslink records are right, but the hash is failing to resolve.

**Comment by Mr0grog** [comment]
To be clear here:

- The domain is owned by Protocol Labs, and so far as I know, our DNS (and dnslink) records can only be modified by Protocol Labs folks.
- The site is served by the public IPFS gateways using dnslink (a specially-formatted DNS TXT record and `A` record pointing to the IPFS gateway).
- Protocol Labs used to pin the hash for site, but that hash is no longer resolving, so I think it’s been unpinned (probably accidentally).

Who over at Protocol Labs can help us fix this up?

Does anybody have a build of the site that matches our dnslink record?

**Comment by Mr0grog** [comment]
Hmmm, actually, I could have sworn the above was all true when I checked before. But `datatogether.org` no longer has a TXT record for dnslink or even an `A` record pointing to the gateway so far as I can tell. It *is* still owned by Protocol Labs, though…

**Comment by dcwalk** [comment]
@victorb helped most recently, but I believe other folks leading the infra team are best to check with. Maybe @eefahy?

**Comment by Mr0grog** [comment]
FWIW, in the quarterly call after I commented yesterday, @b5 suggested switching to GH Pages for hosting the site (I think we’d still try to post hashes to IPFS if we can; this would mainly be about making that less *critical*). Obviously we’re having trouble making sure things are pinned & DNS records are correct, and Qri apparently had similar problems.

It’d be disappointing to switch away from a distributed-first approach to the site, but nobody seems to have the capacity for managing and keeping on top of this on an ongoing basis 🙁

**Comment by Frijol** [comment]
Planning to resolve by migrating to a different build & deploy process, so closing this issue in favor of https://github.com/datatogether/website/issues/38#issuecomment-501008818
