### ISSUE TITLE
Broader access to CircleCI?

### ISSUE THREAD

**Issue by Frijol** [datatogether/website#78]
@b5 is there a shared login for CircleCI so other admins can see deployment logs?

**Comment by b5** [comment]
shouldn't need any kind of special access. The ci URL is public: https://circleci.com/gh/datatogether/website

**Comment by b5** [comment]
As for access, CircleCI derives it's access control from github, so if you log in with github & have access to the data together project, you should be able to affect CI settings

**Comment by Frijol** [comment]
Oh that's great! Issue resolution can then just be a link in the readme (which I might get around to today)
