### ISSUE TITLE
Some links are broken on `/readings` page

### ISSUE THREAD

**Issue by lightandluck** [datatogether/website#83]
The `join` link and links to semester notes are broken on https://datatogether.org/readings/. They point to github page urls: `datatogether.github.io` that respond with a 404. Not sure how to fix this correctly. But think it might have to do with `config.toml`. 

![Screen Shot 2019-11-07 at 12 32 59 PM](https://user-images.githubusercontent.com/3014813/68425347-c6aafb00-015a-11ea-8bbf-0304c2b4225b.png)

I don't understand how the github page interacts with the `.org` site, but there seems to be re-direction of some kind. This link `https://datatogether.github.io/website/posts/02_civics/` on the "alternatives" blog post re-directs and does work for some reason

/cc @Frijol

**Comment by Frijol** [comment]
Thanks for finding this! I'll take a look
