### ISSUE TITLE
Pull index copy out of theme?

### ISSUE THREAD

**Issue by dcwalk** [datatogether/website#9]
Still familiarizing myself with Hugo, but it seems to break pattern that the main page copy is stuck in [` website/themes/datatogether/layouts/index.html
`](https://github.com/datatogether/website/blob/44b1129aa56299084807e890f4d3493eda6ae0f1/themes/datatogether/layouts/index.html)
rather than
[`website/content/`](https://github.com/datatogether/website/tree/44b1129aa56299084807e890f4d3493eda6ae0f1/content)

can change this?

**Comment by b5** [comment]
Is good idea. Let's _make that change_
